steps:
  # Fetch up-to-date submodules
  - name: gcr.io/cloud-builders/git
    args: [ 'submodule', 'update', '--init', '--recursive' ]

  # Build with Java's Gradle
  - name: 'gradle:8.4.0-jdk11'
    entrypoint: "bash"
    args: [ "-c", "./gradlew --no-daemon build"]

  # Create the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:latest", "-f", "dockerfile", "."]

  # Save the image in Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME", "--all-tags"]

#  # Deploy image on service
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: gcloud
#    args: ['run','deploy','${_SERVICE_NAME}','--image','gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA','--region','europe-west9','--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME'

timeout: 20m
